#!/bin/sh
Help(){
        echo "This script only works if you do have Ejabberd installed in your server."
        echo "Usage: xmppsend {from} {to} {message}"
}

if [ $# -ne 3 ]
then
        Help
        exit 1
fi

ejabberdctl send_message chat "${1}@pmmg.mg.gov.br" "$2@pmmg.mg.gov.br" "" "[`date +%Y-%m-%d-%H:%M`]-${3}"
